---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: http-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/devops/task3/test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: http-claim
  labels:
    env: prod
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: http
   labels:
      env: prod
      reg: IN
spec:
  replicas: 1
  selector:
     matchLabels:
        env: prod
        reg: IN
  template:
     metadata:
        name: http-pod
        labels:
           env: prod
           reg: IN
     spec:
       containers:
          - name: http-pod-con
            image: httpd:latest
            ports:
               - containerPort: 80
                 name: "http-servver"
            volumeMounts:
                - name : http-vol
                  mountPath: "/usr/local/apache2/htdocs"
       volumes:
          - name: http-vol
            persistentVolumeClaim:
                 claimName: http-claim
---
apiVersion: v1
kind: Service
metadata:
  name: my-http-service
  labels:
    env: prod
spec:
  selector:
    env: prod
    reg: IN
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
  type: NodePort
---