---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/devops/task3/test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-claim
  labels:
    env: prod
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: php
   labels:
      env: prod
      reg: IN
spec:
  replicas: 1
  selector:
     matchLabels:
        env: prod
        reg: IN
  template:
     metadata:
        name: php-pod
        labels:
           env: prod
           reg: IN
     spec:
       containers:
          - name: php-pod-con
            image: php:7.2-apache
            ports:
               - containerPort: 80
                 name: "php-servver"
            volumeMounts:
                - name : php-vol
                  mountPath: "/var/www/html"
       volumes:
          - name: php-vol
            persistentVolumeClaim:
                 claimName: php-claim
---
apiVersion: v1
kind: Service
metadata:
  name: my-php-service
  labels:
    env: prod
spec:
  selector:
    env: prod
    reg: IN
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
  type: NodePort
---